CREATE DATABASE QUAN_LY_NHA_SACH
GO

--USE QUAN_LY_NHA_SACH
--GO

------------ SACH ------------
CREATE TABLE NHACUNGCAP
(
	MANCC VARCHAR(6),
	TENNCC NVARCHAR(100) NOT NULL,
	DIACHI NVARCHAR(200)NOT NULL,
	DIENTHOAI NVARCHAR(15) NOT NULL,
	EMAIL NVARCHAR(150) NOT NULL,
	TIENNO MONEY NOT NULL DEFAULT 0,
	CONSTRAINT PK_NHACUNGCAP PRIMARY KEY(MANCC)
)
GO

CREATE TABLE NHAXUATBAN
(
	MANXB VARCHAR(6),
	TENNXB NVARCHAR(100) NOT NULL
	CONSTRAINT PK_NHAXUATBAN PRIMARY KEY(MANXB)
)
GO


CREATE TABLE TACGIA
(
	MATG VARCHAR(6),
	TENTG NVARCHAR(100) NOT NULL
	CONSTRAINT PK_TACGIA PRIMARY KEY(MATG)
)
GO

CREATE TABLE THELOAI
(
	MATHELOAI VARCHAR(6),
	TENTHELOAI NVARCHAR(100) NOT NULL,
	CONSTRAINT PK_THELOAI PRIMARY KEY(MATHELOAI)
)
GO

CREATE TABLE SACH
(
	MASACH VARCHAR(6),
	TENSACH NVARCHAR(100) NOT NULL,
	DONVITINH NVARCHAR(50) DEFAULT 'cuốn',
	GIANHAP MONEY CHECK (GIANHAP >= 0),
	GIABAN MONEY CHECK (GIABAN >= 0),
	MANCC VARCHAR(6) CONSTRAINT FK_NCC FOREIGN KEY REFERENCES NHACUNGCAP(MANCC),
	MANXB VARCHAR(6) CONSTRAINT FK_NXB FOREIGN KEY REFERENCES NHAXUATBAN(MANXB),
	MATG VARCHAR(6) CONSTRAINT FK_TG FOREIGN KEY REFERENCES NHACUNGCAP(MANCC),
	MATHELOAI VARCHAR(6) CONSTRAINT FK_TL FOREIGN KEY REFERENCES THELOAI(MATHELOAI),
	SOLUONGTON INT DEFAULT 0,
	MOTA NTEXT,
	HINHMINHHOA VARCHAR(50),
	CONSTRAINT PK_SACH PRIMARY KEY(MASACH)
)
GO

--------------- PHÂN QUYỀN TÀI KHOẢN ĐĂNG NHÂP ---------------
CREATE TABLE NHANVIEN
(
	MANV VARCHAR(6),
	TENNV NVARCHAR(50) NOT NULL,
	DIACHI NVARCHAR(200)NOT NULL,
	DIENTHOAI NVARCHAR(15) NOT NULL,
	EMAIL NVARCHAR(150) NOT NULL,
	GIOITINH BIT DEFAULT 0,
	NGAYSINH SMALLDATETIME CHECK(YEAR(NGAYSINH) < 2021),
	NGAYVAOLAM SMALLDATETIME,
	CONSTRAINT PK_NHANVIEN PRIMARY KEY(MANV)
)
GO

CREATE TABLE TAIKHOAN
(
	MATAIKHOAN VARCHAR(6),
	TENTAIKHOAN VARCHAR(20),
	MATKHAU VARCHAR(20) UNIQUE,
	LOAITAIKHOAN BIT DEFAULT 0,
	CONSTRAINT PK_TAIKHOAN PRIMARY KEY(MATAIKHOAN),
	MANV VARCHAR(6)CONSTRAINT FK_NV_TK FOREIGN KEY REFERENCES NHANVIEN(MANV)
)

------------ BAN HANG ------------
CREATE TABLE HOADON
(
	MAHD VARCHAR(6),
	NGAYLAP SMALLDATETIME,
	TONGTIEN MONEY CHECK (TONGTIEN >= 0) DEFAULT 0 ,
	NHANVIEN VARCHAR(6) CONSTRAINT FK_NVHD FOREIGN KEY REFERENCES NHANVIEN(MANV),
	CONSTRAINT PK_HD PRIMARY KEY(MAHD)
)
GO

CREATE TABLE CT_HOADON
(
	MAHD VARCHAR(6) CONSTRAINT FK_HD FOREIGN KEY REFERENCES HOADON(MAHD),
	MASACH VARCHAR(6) CONSTRAINT FK_HD_SACH FOREIGN KEY REFERENCES SACH(MASACH),
	SOLUONG INT CHECK(SOLUONG > 0),
	GIABAN DECIMAL(9,2) CHECK(GIABAN >= 0),
	THANHTIEN AS SOLUONG * GIABAN,
	CONSTRAINT PK_CTHOADON PRIMARY KEY(MAHD,MASACH)
)
GO

------------ NHAP SACH ------------
CREATE TABLE PHIEUNHAPSACH
(
	MAPHIEU VARCHAR(6),
	NGAYLAP SMALLDATETIME,
	TONGTIEN MONEY CHECK (TONGTIEN >= 0),
	DATRA MONEY,
	CONNO AS TONGTIEN - DATRA,
	NHACUNGCAP VARCHAR(6) CONSTRAINT FK_NCCPHIEUNHAP FOREIGN KEY REFERENCES NHACUNGCAP(MANCC),
	NHANVIEN VARCHAR(6) CONSTRAINT FK_NVPHIEUNHAP FOREIGN KEY REFERENCES NHANVIEN(MANV),
	CONSTRAINT PK_PHIEUNHAPSACH  PRIMARY KEY(MAPHIEU)
)
GO

CREATE TABLE CT_PHIEUNHAPSACH
(
	MAPHIEU VARCHAR(6) CONSTRAINT FK_PHIEUNHAP FOREIGN KEY REFERENCES PHIEUNHAPSACH(MAPHIEU),
	MASACH VARCHAR(6) CONSTRAINT FK_PHIEUNHAP_SACH FOREIGN KEY REFERENCES SACH(MASACH),
	SOLUONG INT CHECK(SOLUONG > 0),
	GIANHAP DECIMAL(9,2) CHECK(GIANHAP>=0),
	THANHTIEN AS SOLUONG * GIANHAP,
	CONSTRAINT PK_CTPHIEUNHAP PRIMARY KEY(MAPHIEU,MASACH)
)
GO

/*
CREATE TABLE KHUYENMAI
(
	MAKHUYENMAI VARCHAR(6),
	NGAYBATDAU SMALLDATETIME,
	NGAYKETTHUC SMALLDATETIME,
	TENKM NVARCHAR(100) NOT NULL,
	GIAGIAM INT,
	CHITIET TEXT,
	CONSTRAINT PK_KHUYENMAI PRIMARY KEY(MAKHUYENMAI)
)
GO

CREATE TABLE CT_KHUYENMAI
(
	MAKM INT CONSTRAINT FK_KM FOREIGN KEY REFERENCES KHUYENMAI(MAKHUYENMAI),
	MASACH INT CONSTRAINT FK_KM_SACH FOREIGN KEY REFERENCES SACH(MASACH),
	GIAKHUYENMAI MONEY,
	CONSTRAINT PK_DONDATHANG PRIMARY KEY(MAKM,MASACH)
)
GO*/

--------------- BÁO CÁO ---------------
CREATE TABLE THAMSO
(
	TONTOIDA INT NOT NULL DEFAULT 300,
	TONTOITHIEU INT NOT NULL DEFAULT 20,
	NHAPTOITHIEU INT DEFAULT 150,
	TILETINHDONGIA FLOAT DEFAULT 150,
	QUYDINH INT DEFAULT 1,
)
GO

CREATE TABLE BAOCAOTON
(
	MABAOCAO VARCHAR(6),
	LOAIBC INT DEFAULT 0,
	NGAYLAP SMALLDATETIME,
	NHANVIEN VARCHAR(6) CONSTRAINT FK_NVLBCTON FOREIGN KEY REFERENCES NHANVIEN(MANV),
	MASACH VARCHAR(6) CONSTRAINT FK_BCTON_SACH FOREIGN KEY REFERENCES SACH(MASACH),
	TONDAU INT,
	TONCUOI INT,
	PHATSINH INT,
	CONSTRAINT PK_BCTON PRIMARY KEY(MABAOCAO)
)
GO

CREATE TABLE BAOCAONO
(
	THANG INT,
	NAM INT,
	NGAYLAP SMALLDATETIME,
	NGUOILAP INT CONSTRAINT FK_NVLAPBCNO FOREIGN KEY REFERENCES NHANVIEN(MANHANVIEN),
	MANHACUNGCAP INT CONSTRAINT FK_NCC_BCNO FOREIGN KEY REFERENCES NHACUNGCAP(MANHACUNGCAP),
	NOCU INT,
	PHATSINH INT,
	NOMOI INT,
	CONSTRAINT PK_BCNO PRIMARY KEY(THANG,NAM)
)
GO



-- TRIGGER --
--1.Ngày tạo hóa đơn < ngày vào làm của nhân viên -- 
	--Tren bang HOADON: them, cap nhat --
CREATE TRIGGER NGHD_NGVL_HOADON ON HOADON 
FOR INSERT, UPDATE AS 
	BEGIN 
		DECLARE @MANV int , @NGVL SMALLDATETIME, @NGHD SMALLDATETIME 
		SELECT @MANV = NguoiLap, @NGHD = NgayLap 
		FROM inserted 
		SELECT @NGVL=  NgayVaoLam
		FROM NHANVIEN 
		WHERE @MANV = MaNhanVien  
		IF EXISTS (SELECT * FROM inserted I, NHANVIEN N WHERE I.NguoiLap = N.MaNhanVien AND I.NgayLap < N.NgayVaoLam) 
			BEGIN 
				PRINT(N'Lỗi Ngày lập Hóa đơn   < Ngày vào làm  của nhân viên!') 
				ROLLBACK TRAN 
			END 
	END 
	--tren bang nhan vien: cap nhat--
	CREATE TRIGGER NGHD_NGVL_NHANVIEN ON NHANVIEN 
	FOR UPDATE AS 
		BEGIN 
			DECLARE @MANV int , @NGVL SMALLDATETIME, @NGHD SMALLDATETIME 
			SELECT @MANV = MaNhanVien, @NGVL = NgayVaoLam 
			FROM inserted 
			SELECT @NGHD 
			FROM HOADON 
			WHERE @MANV = NguoiLap 
			IF EXISTS (SELECT * FROM inserted I, HOADON H WHERE I.MANV = H.MANV AND H.NGHD < I.NGVL) 		
				BEGIN 
					PRINT(N'Ngày vào làm  của nhân viên > Ngày lập Hóa đơn!') 
					ROLLBACK TRAN 
				END 
		END 
--2.Tính Tongtien Hóa đơn -- 
-- INSERT 1 CT_HOADON mới thì TongTien trong HOADON TĂNG, số lượng sách trong kho sẽ giảm = số lượng trong kho - số lượng bán --- 

CREATE TRIGGER TRG_INS_CTHD ON CT_HOADON 
FOR INSERT 
AS BEGIN 
	UPDATE HOADON SET TongTien = TongTien  + I.ThanhTien
	FROM INSERTED I 
	WHERE I.MAHD=HOADON.MaHoaDon 
	UPDATE SACH SET SoLuongTon= SoLuongTon - I.Soluong
	FROM INSERTED I 
	WHERE I.MaSach=SACH.MaSach 
END 

-- DELETE 1 CT_HOADON mới thì TongTien trong HOADON giảm , số lượng sách trong kho sẽ tăng về lại --- 

CREATE TRIGGER TRG_DEL_CTHD ON CT_HOADON FOR DELETE 
AS BEGIN 
UPDATE HOADON SET TongTien = TongTien  - D.ThanhTien 
FROM DELETED D 
WHERE HOADON.MaHoaDon=D.MAHD 
UPDATE SACH SET SoLuongTon= SoLuongTon + I.Soluong
	FROM INSERTED I 
	WHERE I.MaSach=SACH.MaSach 
END 
--3. Xóa 1 Hóa đơn thì xóa các chi tiết hóa đơn cuar nó-- 
CREATE TRIGGER TRG_DEL_HOADON ON HOADON 
FOR DELETE 
AS BEGIN 
	DECLARE @MAHD int 
	SELECT @MAHD = MaHoaDon
	FROM DELETED D
	delete from CT_HOADON
	where CT_HOADON.MaHD = @MAHD
END 

-- 4.Ngày lập phiếu nhập sách >= ngày vào làm của nhân viên --
	--Tren bang PhieuNhapSach: them, cap nhat --
CREATE TRIGGER NGLP_NGVL_PhieuNhapSach ON PhieuNhapSach 
FOR INSERT, UPDATE AS 
	BEGIN 
		DECLARE @MANV int , @NGVL SMALLDATETIME, @NGLP SMALLDATETIME 
		SELECT @MANV = NguoiLap, @NGLP = NgayLap 
		FROM inserted 
		SELECT @NGVL=  NgayVaoLam
		FROM NHANVIEN 
		WHERE @MANV = MaNhanVien  
		IF EXISTS (SELECT * FROM inserted I, NHANVIEN N WHERE I.NguoiLap = N.MaNhanVien AND I.NgayLap < N.NgayVaoLam) 
			BEGIN 
				PRINT(N'Lỗi Ngày lập Phiếu nhập sách   < Ngày vào làm  của nhân viên!') 
				ROLLBACK TRAN 
			END 
	END 
	--tren bang nhan vien: cap nhat--
	CREATE TRIGGER NGLP_NGVL_NHANVIEN ON NHANVIEN 
FOR UPDATE AS 
BEGIN 
	DECLARE @MANV int , @NGVL SMALLDATETIME, @NGLP SMALLDATETIME 
	SELECT @MANV = MaNhanVien, @NGVL = NgayVaoLam 
	FROM inserted 
	SELECT @NGLP =  NgayLap 
	FROM PhieuNhapSach 
	WHERE @MANV = NguoiLap 
	IF EXISTS (SELECT * FROM inserted I, PhieuNhapSach H WHERE I.MaNhanVien = H.NguoiLap AND H.NgayLap < I.NgayVaoLam) 		
	BEGIN 
		PRINT(N'Lỗi Ngày vào làm  của nhân viên > Ngày lập Phiếu nhập sách ') 
		ROLLBACK TRAN 
	END 
END 
--5.Tính TongTien Phiếu Nhập Sách và cập nhật số lượng sách trong kho khi nhập sách  -- 
	--- INSERT 1 CT_PhieuNhapSach   mới thì TongTien trong PhieuNhapSach   TĂNG đồng thời tăng  số lượng sách trong kho = số lượng trong kho + số lượng nhập--- 

CREATE TRIGGER TRG_INS_CTNHAPSACH  ON CT_PhieuNhapSach 
FOR INSERT 
AS BEGIN 
	UPDATE PhieuNhapSach SET TongTien = TongTien  + I.ThanhTien
	FROM INSERTED I 
	WHERE I.MaPhieu=PhieuNhapSach.MaPhieu 
	UPDATE SACH SET SoLuongTon= SoLuongTon + I.Soluong
	FROM INSERTED I 
	WHERE I.MaSach=SACH.MaSach 
END 

	--- DELETE 1 1 CT_PhieuNhapSach   mới thì TongTien trong PhieuNhapSachGiảm  đồng thời giảm về lại  số lượng sách trong kho ban đầu--- 

CREATE TRIGGER TRG_DEL_CTNHAPSACH ON CT_PhieuNhapSach
FOR DELETE 
AS BEGIN 
UPDATE PhieuNhapSach SET TongTien = TongTien  - D.ThanhTien 
FROM DELETED D 
WHERE D.MaPhieu=PhieuNhapSach.MaPhieu 
UPDATE SACH SET SoLuongTon= SoLuongTon - I.Soluong
	FROM INSERTED I 
	WHERE I.MaSach=SACH.MaSach 
END 

--6.Cập nhật nợ của nhà cung cấp  khi nhập sách --
	-- Thêm 1 Phiếu nhập --
CREATE TRIGGER TRG_INS_NHAPSACH ON PhieuNhapSach 
FOR INSERT, Update  
AS BEGIN 
	UPDATE NHACUNGCAP SET TienNo = TienNo  + I.ConNo 
	FROM INSERTED I 
	WHERE I.NhaCungCap=NHACUNGCAP.MaNhaCungCap 
END 
	-- Xóa 1 phiếu nhập Xóa các CT_NhapSach liên quan và cập nhật lại tiền nợ,chỉ  xóa khi đã tạo thành công nhưng muốn hủy ko nhập nữa ! --
CREATE TRIGGER TRG_DEL_NHAPSACH ON PhieuNhapSach 
FOR DELETE 
AS BEGIN 
	DECLARE @MAPhieu int,  @TienNo money , @MANCC int 
	SELECT @MAPhieu = MaPhieu, @TienNo=ConNo, @MANCC=NhaCungCap
	FROM DELETED D 
	UPDATE NHACUNGCAP SET TienNo = TienNo  - @TienNo
	WHERE @MANCC=NHACUNGCAP.MaNhaCungCap
	DELETE from CT_PhieuNhapSach
	Where @MAPhieu  = CT_PhieuNhapSach.MaPhieu
END 




--PROCEDURE --
--1.Xóa Hóa đơn -> xóa các thông tin liên quan --
create proc Proc_XoaHOADON (@mshd int)
as
begin

       -- MShd đã có trong bảng HOADON --
       if(exists(select * from HOADON where @mshd=MaHoaDon))
       begin

             -- Vô hiệu hóa các ràng buộc liên quan đến bảng HOADON --
             alter table HOADON  nocheck Constraint all
             alter table CT_HOADON nocheck Constraint all

             ------ Gửi lệnh delete để thực thi trigger ------
             delete from HOADON
             where MaHoaDon=@mshd

             -- Sau khi xóa, kích hoạt các ràng buộc liên quan đến bảng HOADON --
             alter table HOADON check Constraint all
             alter table CT_HOADON check Constraint all
         
       end
	   -- nếu không tồn tại đề tài -- 
       else
       begin
             -- thông báo --
             print N'Lỗi. Mã hóa đơn ' + @mshd + N' không tồn tại'
             return 0
       end    
end
--2.Xóa khuyến mãi -> xóa các thông tin liên quan --
--3.Xóa phiếu nhập sách => xóa các thông tin liên quan --
--4.Kiểm tra xem nhập sách có đúng qui định ko : số lượng sách nhập tối thiểu, số lượng sách tồn kho --
--5.Kiểmm tra bán sách có đúng qui định: số lượng trong kho còn đur bán hay ko? --
--- Tìm kiếm sách --
--- Tìm kiếm sách theo mã, tên , tác giả, nhà cung cấp, nhà xuất bản, thể loại --
-- Tìm kiếm nhà cung cấp--
-- Tìm kiếm khuyễn mãi --
-- Tính tiền hóa đơn khi áp dụng mã khuyến mãi --
-- Thống kê hóa đơn, doanh số nhân viên bán được theo ngày, tuần , tháng --
-- Thống kê nợ --
-- Thống kê tồn kho --
-- Set nợ của nhà cung cấp về 0 khi admin thanh toán hết nợ -- 